# .github/workflows/cleanup-old-branches.yml
name: Cleanup Old Trusted Branches

on:
  schedule:
    # Runs every day at midnight UTC
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  cleanup:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Setup Git
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com

      - name: Fetch branches
        run: |
          # Fetch all branches
          git fetch --all

          # Get the current date in seconds since the epoch
          CURRENT_DATE=$(date +%s)

          # List branches starting with 'temp-ci-trusted-fork' and their last commit dates in '%Y-%m-%d' format
          git for-each-ref --format='%(refname:short) %(committerdate:iso8601)' refs/heads/ | grep 'temp-ci-trusted-fork' | while read branch commit_date; do
            # Convert the commit date to seconds since the epoch
            COMMIT_DATE_IN_SEC=$(date -d "$commit_date" +%s)

            # Calculate the age of the branch in days
            AGE=$(( (CURRENT_DATE - COMMIT_DATE_IN_SEC) / 86400 ))

            if [ $AGE -ge 7 ]; then
              echo "Deleting branch: $branch (Age: $AGE days)"
              git push origin --delete "$branch"
            fi
          done
